# -*- coding: utf-8 -*-
"""final_aps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feMg5uat5hC2D38RgFU7Nn2MAJHHW33j
"""

# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np

# =============================
# 1. LOAD AND PREPROCESS DATA
# =============================

file_name = 'training_session.csv'
df = pd.read_csv(file_name, header=None)

# Assign 8 column names
df.columns = [
    'first_name', 'last_name', 'gender', 'col_d',
    'category', 'assessment', 'score', 'timestamp'
]

# Convert types
df['score'] = pd.to_numeric(df['score'], errors='coerce')
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

# Drop rows with missing score
df = df.dropna(subset=['score']).copy()

# Clean text columns
text_cols = ['first_name', 'last_name', 'gender', 'col_d', 'category', 'assessment']
for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

# Combine category and assessment
df['category_assessment'] = df['category'] + ' ' + df['assessment']

# Map age groups
age_map = {
    'A': 1, 'B': 1,
    'C': 2, 'D': 2,
    'E': 3, 'F': 3
}
df['age_group'] = df['col_d'].map(age_map)

# Standardize gender
df['gender_clean'] = df['gender'].str.upper().str[0]

# Keep only M / F if possible
df['gender_clean'] = df['gender_clean'].replace({
    'M': 'M',
    'F': 'F'
})

# Create cohort column
df['cohort'] = df['age_group'].astype('Int64').astype(str) + "_" + df['gender_clean']

# Drop rows with invalid cohort pieces
df = df[
    df['age_group'].notna() &
    df['gender_clean'].isin(['M', 'F'])
].copy()

# Optional: remove impossible or zero/negative scores if needed
# df = df[df['score'] > 0].copy()

print("Preprocessed shape:", df.shape)
df.head()

# ============================================
# 2. DEFINE SCORE DIRECTION FOR EACH ASSESSMENT
# ============================================

higher_is_better_map = {
    # Lower is better
    'Broad Jump 5-10-5 Shuttles': False,
    'Circuit Training Knockout': False,
    'Circuit Training Knockout-Obstacle': False,
    'Freelap 10yd Dash': False,
    'Freelap 10yd Dash Ball': False,
    'Freelap 20yd Dash': False,
    'Freelap 20yd Dash Ball': False,
    'RoxPro 5-10-5 shuttle': False,
    'RoxPro Sprint-10 yrd': False,


    # Higher is better
    'Broad Jump Horizontal': True,
    'Circuit Training Maestro': True,
    'Circuit Training Pass Find 1': True,
    'Circuit Training Vision': True,
    'Fast Feet Architect': True,
    'Fast Feet Maestro': True,
    'Fast Feet Vision': True,
    'ICON 4M Architect': True,
    'ICON 4M Maestro': True,
    'ICON 4M Vision': True,
    'ICON Q Pass Find 2': True,
    'ICON V2 Architect': True,
    'ICON V2 Maestro': True,
    'ICON V2 Vision': True,
    'Reflexion Edge Hand Eye Coordination': True,
    'Reflexion Edge Inhibition': True,
    'Reflexion Edge Prioritization': True,
    'Reflexion Edge Reaction Time': True,
    'Reflexion Edge Tracking': True,
    'Tech Touch Ground & Tech Touch Air Receive 10 Air': True,
    'Tech Touch Ground & Tech Touch Air Receive 10 Ground': True,
    'Tech Touch One Touch Pass Pass 10 Air': True,
    'Tech Touch One Touch Pass Pass 10 Ground': True,
    'Vertical Jump Vertical': True,
    # Assessments from the new data
    'Circuit Maestro': True,
    'Circuit Vision': True,
    'Circuit Pass find 1': True,
    'ICON Q Pass find 2': True,
    'ICON 4M Vision': True,
    'ICON V2 Maestro': True,
    'TechTouch 1st Touch - Air': True,
    'TechTouch 1st touch - ground': True,
    'RoxPro 5-10-5 shuttle': False,
    'RoxPro Sprint-10 yrd': False,
    'Vision Wall GO 360': True,
    'Vision Wall Scan & React': True,
    'Vision Wall Large to Small': True,
    'Vision Wall Balance Reaction': True,
}

DEFAULT_HIGHER_IS_BETTER = True

df['higher_is_better'] = (
    df['category_assessment']
    .map(higher_is_better_map)
    .fillna(DEFAULT_HIGHER_IS_BETTER)
)

# ============================================
# LOG TRANSFORMATIONS
# ============================================

log_transform_assessments = [
    'Circuit Training Knockout',
    'Circuit Training Knockout-Obstacle',
    'Freelap 10yd Dash',
    'Freelap 10yd Dash Ball',
    'Freelap 20yd Dash',
    'Freelap 20yd Dash Ball',
    'RoxPro 5-10-5 shuttle',
    'RoxPro Sprint-10 yrd'
]

mask = df['category_assessment'].isin(log_transform_assessments)

df.loc[mask, 'score'] = np.log(
    pd.to_numeric(df.loc[mask, 'score'], errors='coerce')
)

# ==========================================================
# 3. CREATE SCORING INPUT USING MOST RECENT PLAYER SCORE ONLY
# ==========================================================

# For APS and RPS, use only the most recent score for each player-assessment.
# This keeps your original df intact and creates a separate scoring_df.

player_cols = ['first_name', 'last_name', 'gender_clean', 'age_group']

scoring_df = (
    df.sort_values('timestamp')
      .drop_duplicates(subset=player_cols + ['category_assessment'], keep='last')
      .copy()
)

print("Scoring input shape (most recent attempt only):", scoring_df.shape)

# ==========================================================
# 3. APS BENCHMARKS + WEIGHTED RECENT APS SYSTEM
# ==========================================================

MIN_COHORT_N = 30
APS_SCORE_COL = "APS"
player_cols = ["first_name", "last_name", "gender_clean", "age_group"]

# ----------------------------------------------------------
# A. CATEGORY MAPPING
# ----------------------------------------------------------

def map_assessment_category(assessment):
    if pd.isna(assessment):
        return np.nan

    a = str(assessment).lower()

    if "circuit" in a:
        return "Dribbling"

    elif "icon" in a:
        return "Passing"

    elif (
        "tech touch" in a
        or "techtouch" in a
        or "1st touch" in a
        or "one touch" in a
    ):
        return "First Touch"

    elif (
        "5-10-5" in a
        or "shuttle" in a
        or "sprint" in a
        or "10yd" in a
        or "10 yd" in a
        or "10yrd" in a
        or "10 yrd" in a
        or "dash" in a
    ):
        return "Agility"

    elif (
        "go 360" in a
        or "scan" in a
        or "react" in a
        or "reaction" in a
        or "large to small" in a
        or "small to large" in a
        or "balance" in a
        or "vision wall" in a
        or "roxpro" in a
        or "reflection edge" in a
    ):
        return "Vision"

    else:
        return "Unmapped"


df["aps_category"] = df["category_assessment"].apply(map_assessment_category)


# ----------------------------------------------------------
# B. USE MOST RECENT PLAYER-ASSESSMENT ONLY FOR BENCHMARKS
# ----------------------------------------------------------

benchmark_base = (
    df.sort_values("timestamp")
      .drop_duplicates(subset=player_cols + ["category_assessment"], keep="last")
      .copy()
)

cohort_sizes = (
    benchmark_base
    .groupby(["category_assessment", "cohort"])
    .size()
    .reset_index(name="n_original_cohort")
)

benchmark_base = benchmark_base.merge(
    cohort_sizes,
    on=["category_assessment", "cohort"],
    how="left"
)

benchmark_base["benchmark_type"] = np.where(
    benchmark_base["n_original_cohort"] < MIN_COHORT_N,
    "age_group",
    "age_gender"
)

benchmark_base["combined_for_small_sample"] = (
    benchmark_base["n_original_cohort"] < MIN_COHORT_N
)

benchmark_base["aps_distribution_used"] = np.where(
    benchmark_base["combined_for_small_sample"],
    "Combined with same age group across gender",
    "Original age-gender cohort"
)

benchmark_base["benchmark_cohort"] = np.where(
    benchmark_base["benchmark_type"] == "age_group",
    benchmark_base["age_group"].astype(str),
    benchmark_base["cohort"]
)


# ----------------------------------------------------------
# C. CREATE TRUE AGE-GROUP BENCHMARK SOURCE
# ----------------------------------------------------------

benchmark_source_age_gender = benchmark_base.copy()
benchmark_source_age_gender["benchmark_cohort"] = benchmark_source_age_gender["cohort"]

benchmark_source_age = benchmark_base.copy()
benchmark_source_age["benchmark_cohort"] = benchmark_source_age["age_group"].astype(str)

benchmark_source = pd.concat(
    [benchmark_source_age_gender, benchmark_source_age],
    ignore_index=True
)


# ----------------------------------------------------------
# D. BUILD BENCHMARK TABLE
# ----------------------------------------------------------

benchmark_quantiles = [0.30, 0.50, 0.70, 0.90]

benchmark_table = (
    benchmark_source
    .groupby(["category_assessment", "benchmark_cohort"])["score"]
    .quantile(benchmark_quantiles)
    .unstack()
    .reset_index()
)

benchmark_table.columns = [
    "category_assessment", "benchmark_cohort",
    "q30", "q50", "q70", "q90"
]

sample_sizes = (
    benchmark_source
    .groupby(["category_assessment", "benchmark_cohort"])
    .size()
    .reset_index(name="n_benchmark_distribution")
)

benchmark_table = benchmark_table.merge(
    sample_sizes,
    on=["category_assessment", "benchmark_cohort"],
    how="left"
)


# ----------------------------------------------------------
# E. ADD BENCHMARK COHORT INFO BACK TO ALL ATTEMPTS
# ----------------------------------------------------------

benchmark_lookup = benchmark_base[
    [
        "first_name", "last_name", "gender_clean", "age_group",
        "category_assessment", "n_original_cohort",
        "benchmark_type", "combined_for_small_sample",
        "aps_distribution_used", "benchmark_cohort"
    ]
].drop_duplicates()

scoring_df = df.merge(
    benchmark_lookup,
    on=player_cols + ["category_assessment"],
    how="left"
)

scoring_df = scoring_df.merge(
    benchmark_table,
    on=["category_assessment", "benchmark_cohort"],
    how="left"
)


# ----------------------------------------------------------
# F. APS SCORING FUNCTION
# ----------------------------------------------------------

def interpolate_score(x, x0, x1, y0, y1):
    if pd.isna(x0) or pd.isna(x1) or x1 == x0:
        return np.nan
    return y0 + (x - x0) * (y1 - y0) / (x1 - x0)


def aps_from_benchmarks(score, q30, q50, q70, q90, higher_is_better=True):
    if any(pd.isna(v) for v in [score, q30, q50, q70, q90]):
        return np.nan

    if not higher_is_better:
        score = -score
        q30, q50, q70, q90 = sorted([-q90, -q70, -q50, -q30])

    if score <= q30:
        aps = interpolate_score(score, q30 - (q50 - q30), q30, 0, 30)
    elif score <= q50:
        aps = interpolate_score(score, q30, q50, 30, 50)
    elif score <= q70:
        aps = interpolate_score(score, q50, q70, 50, 70)
    elif score <= q90:
        aps = interpolate_score(score, q70, q90, 70, 90)
    else:
        aps = interpolate_score(score, q90, q90 + (q90 - q70), 90, 100)

    return float(np.clip(aps, 0, 100))


def assign_aps_band(score):
    if pd.isna(score):
        return np.nan
    elif score < 30:
        return "Foundation"
    elif score < 50:
        return "Developing"
    elif score < 70:
        return "Approaching"
    elif score < 90:
        return "Strong"
    else:
        return "Elite"


scoring_df["APS"] = scoring_df.apply(
    lambda row: aps_from_benchmarks(
        score=row["score"],
        q30=row["q30"],
        q50=row["q50"],
        q70=row["q70"],
        q90=row["q90"],
        higher_is_better=row["higher_is_better"]
    ),
    axis=1
)

scoring_df["APS_band_raw_attempt"] = scoring_df["APS"].apply(assign_aps_band)


# ----------------------------------------------------------
# G. WEIGHT MOST RECENT SCORES PER PLAYER + ASSESSMENT
# ----------------------------------------------------------

def get_recent_weights(n):
    if n == 1:
        return [1.0]
    elif n == 2:
        return [2/3, 1/3]
    else:
        return [0.5, 0.3, 0.2]


valid_scores = (
    scoring_df
    .dropna(subset=["APS", "aps_category", "timestamp"])
    .query("aps_category != 'Unmapped'")
    .copy()
)


def weighted_recent_assessment_score(group):
    group = group.sort_values("timestamp", ascending=False).head(3).copy()

    weights = get_recent_weights(len(group))
    group["recent_weight"] = weights

    weighted_score = np.average(group["APS"], weights=group["recent_weight"])

    return pd.Series({
        "weighted_assessment_aps": weighted_score,
        "individual_assessment_band": assign_aps_band(weighted_score),
        "n_recent_scores_used": len(group),
        "latest_assessment_date": group["timestamp"].max(),
        "weights_used": ", ".join([str(round(w, 3)) for w in weights]),
        "raw_attempt_aps_used": ", ".join([str(round(v, 1)) for v in group["APS"]])
    })


assessment_recent_scores = (
    valid_scores
    .groupby(player_cols + ["aps_category", "category_assessment"], as_index=False)
    .apply(weighted_recent_assessment_score)
    .reset_index(drop=True)
)

assessment_recent_scores["weighted_assessment_aps"] = (
    assessment_recent_scores["weighted_assessment_aps"].round(1)
)


# ----------------------------------------------------------
# H. CATEGORY SCORES
# ----------------------------------------------------------

category_scores = (
    assessment_recent_scores
    .groupby(player_cols + ["aps_category"], as_index=False)
    .agg(
        category_aps_score=("weighted_assessment_aps", "mean"),
        n_assessments_used=("category_assessment", "nunique"),
        assessments_used=("category_assessment", lambda x: ", ".join(sorted(x.dropna().unique())))
    )
)

category_scores["category_aps_score"] = category_scores["category_aps_score"].round(1)
category_scores["category_aps_band"] = category_scores["category_aps_score"].apply(assign_aps_band)


# ----------------------------------------------------------
# I. FINAL OVERALL APS SCORE + BAND
# ----------------------------------------------------------

final_aps = (
    category_scores
    .groupby(player_cols, as_index=False)
    .agg(
        final_aps_score=("category_aps_score", "mean"),
        n_categories_used=("aps_category", "nunique")
    )
)

final_aps["final_aps_score"] = final_aps["final_aps_score"].round(1)
final_aps["final_aps_band"] = final_aps["final_aps_score"].apply(assign_aps_band)


# ----------------------------------------------------------
# J. DASHBOARD-FRIENDLY TABLE
# ----------------------------------------------------------

category_scores_wide = category_scores.pivot_table(
    index=player_cols,
    columns="aps_category",
    values="category_aps_score",
    aggfunc="mean"
).reset_index()

final_dashboard_scores = final_aps.merge(
    category_scores_wide,
    on=player_cols,
    how="left"
)

final_dashboard_scores.head()