# -*- coding: utf-8 -*-
"""final_rps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJfRL0twNAGXUC6NE81kG-g_vvBUhF2H
"""

# -*- coding: utf-8 -*-
"""
final_rps.py (replaces Analysis/sigmoid_cohort.py for this repo).

Structured RPS scoring pipeline for Sogility assessment data.

Core scoring requirements
-------------------------
1. Final RPS range: 30 to 99
2. Formula: RPS = 30 + 69 * S(x)
3. Uses 75% span and S_SPAN = 1.0986
4. Lower-is-better assessments are direction-adjusted
5. Log-type assessments are log-transformed inside the scoring function
6. Small age + gender cohorts are handled by dropping gender and using same age group
7. Overall RPS uses recency-weighted attempts:
   - 1 attempt: 100%
   - 2 attempts: most recent 2/3, older 1/3
   - 3+ attempts: most recent 0.50, second 0.30, third 0.20

Important
---------
Do not log-transform score before calling the RPS function.
Do not reduce the input to most recent attempt only. The function needs full history
for recency-weighted overall RPS.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Dict, List, Tuple

import numpy as np
import pandas as pd


# ============================================================
# 1. CONFIGURATION
# ============================================================

RAW_COLUMNS = [
    "first_name",
    "last_name",
    "gender",
    "col_d",
    "category",
    "assessment",
    "score",
    "timestamp",
]

AGE_GROUP_MAP = {
    "A": 1,
    "B": 1,
    "C": 2,
    "D": 2,
    "E": 3,
    "F": 3,
}

LOG_ASSESSMENTS = {
    "Circuit Training Knockout",
    "Circuit Training Knockout-Obstacle",
    "Freelap 10yd Dash",
    "Freelap 10yd Dash Ball",
    "Freelap 20yd Dash",
    "Freelap 20yd Dash Ball",
    "RoxPro 5-10-5 shuttle",
    "RoxPro Sprint-10 yrd",
}

LOWER_IS_BETTER_ASSESSMENTS = {
    "Broad Jump 5-10-5 Shuttles",
    "Circuit Training Knockout",
    "Circuit Training Knockout-Obstacle",
    "Freelap 10yd Dash",
    "Freelap 10yd Dash Ball",
    "Freelap 20yd Dash",
    "Freelap 20yd Dash Ball",
    "RoxPro 5-10-5 shuttle",
    "RoxPro Sprint-10 yrd",
}

# Optional explicit list of known higher-is-better assessments.
# Unlisted assessments default to higher-is-better unless they are in LOWER_IS_BETTER_ASSESSMENTS.
HIGHER_IS_BETTER_ASSESSMENTS = {
    "Broad Jump Horizontal",
    "Circuit Training Maestro",
    "Circuit Training Pass Find 1",
    "Circuit Training Vision",
    "Fast Feet Architect",
    "Fast Feet Maestro",
    "Fast Feet Vision",
    "ICON 4M Architect",
    "ICON 4M Maestro",
    "ICON 4M Vision",
    "ICON Q Pass Find 2",
    "ICON V2 Architect",
    "ICON V2 Maestro",
    "ICON V2 Vision",
    "Reflexion Edge Hand Eye Coordination",
    "Reflexion Edge Inhibition",
    "Reflexion Edge Prioritization",
    "Reflexion Edge Reaction Time",
    "Reflexion Edge Tracking",
    "Tech Touch Ground & Tech Touch Air Receive 10 Air",
    "Tech Touch Ground & Tech Touch Air Receive 10 Ground",
    "Tech Touch One Touch Pass Pass 10 Air",
    "Tech Touch One Touch Pass Pass 10 Ground",
    "Vertical Jump Vertical",
    "Circuit Maestro",
    "Circuit Vision",
    "Circuit Pass find 1",
    "ICON Q Pass find 2",
    "TechTouch 1st Touch - Air",
    "TechTouch 1st touch - ground",
    "Vision Wall GO 360",
    "Vision Wall Scan & React",
    "Vision Wall Large to Small",
    "Vision Wall Balance Reaction",
}


@dataclass(frozen=True)
class RPSConfig:
    """Configuration for the RPS scoring system."""

    span_percentile: float = 0.75
    min_cohort_n: int = 30
    s_span: float = 1.0986
    rps_min: float = 30.0
    rps_max: float = 99.0
    clip_scores: bool = True

    @property
    def rps_range(self) -> float:
        return self.rps_max - self.rps_min


# ============================================================
# 2. DATA LOADING AND PREPROCESSING
# ============================================================

def load_training_data(file_name: str = "training_session.csv") -> pd.DataFrame:
    """
    Load raw Sogility training session data with no header.
    """
    df = pd.read_csv(file_name, header=None)

    if df.shape[1] != len(RAW_COLUMNS):
        raise ValueError(
            f"Expected {len(RAW_COLUMNS)} columns, but found {df.shape[1]} columns."
        )

    df.columns = RAW_COLUMNS
    return df


def preprocess_training_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean raw training data and create modeling columns:
    - category_assessment
    - age_group
    - gender_clean
    - cohort
    - higher_is_better
    """
    data = df.copy()

    required_cols = RAW_COLUMNS
    _validate_columns(data, required_cols)

    data["score"] = pd.to_numeric(data["score"], errors="coerce")
    data["timestamp"] = pd.to_datetime(data["timestamp"], errors="coerce")

    text_cols = [
        "first_name",
        "last_name",
        "gender",
        "col_d",
        "category",
        "assessment",
    ]

    for col in text_cols:
        data[col] = data[col].astype(str).str.strip()

    data["category_assessment"] = data["category"] + " " + data["assessment"]
    data["age_group"] = data["col_d"].map(AGE_GROUP_MAP)
    data["gender_clean"] = data["gender"].str.upper().str[0]

    data = data[
        data["score"].notna()
        & data["timestamp"].notna()
        & data["age_group"].notna()
        & data["gender_clean"].isin(["M", "F"])
    ].copy()

    data["age_group"] = data["age_group"].astype(int)
    data["cohort"] = data["age_group"].astype(str) + "_" + data["gender_clean"]
    data["higher_is_better"] = ~data["category_assessment"].isin(
        LOWER_IS_BETTER_ASSESSMENTS
    )

    return data.reset_index(drop=True)


# ============================================================
# 3. MAP HELPERS
# ============================================================

def build_skill_type_map(log_assessments: Optional[set] = None) -> Dict[str, str]:
    """
    Build skill type map.
    "Log" assessments are log-transformed inside the scoring function.
    All others default to "Normal".
    """
    if log_assessments is None:
        log_assessments = LOG_ASSESSMENTS

    return {assessment: "Log" for assessment in log_assessments}


def build_good_direction_map(lower_is_better_assessments: Optional[set] = None) -> Dict[str, str]:
    """
    Build direction map.
    "Lo" means lower raw score is better.
    All others default to "Hi".
    """
    if lower_is_better_assessments is None:
        lower_is_better_assessments = LOWER_IS_BETTER_ASSESSMENTS

    return {assessment: "Lo" for assessment in lower_is_better_assessments}


# ============================================================
# 4. GENERAL HELPERS
# ============================================================

def _validate_columns(df: pd.DataFrame, required_cols: List[str]) -> None:
    """Raise a clear error if required columns are missing."""
    missing_cols = [col for col in required_cols if col not in df.columns]

    if missing_cols:
        raise ValueError(f"Missing required column(s): {missing_cols}")


def _safe_log(x: float) -> float:
    """Natural log with protection against zero, negative, and missing values."""
    if pd.isna(x) or x <= 0:
        return np.nan
    return float(np.log(x))


def _sigmoid(z: float) -> float:
    """Numerically stable enough sigmoid for this scoring use case."""
    return float(1 / (1 + np.exp(-z)))


def _calculate_sigmoid_rps(
    x: float,
    mid: float,
    span: float,
    config: RPSConfig,
) -> float:
    """
    Calculate RPS using:
        RPS = 30 + 69 * S(x)

    where:
        S(x) = 1 / (1 + exp(-z))
        z = S_SPAN * ((x - mid) / abs(span - mid))
    """
    denom = abs(span - mid)

    if pd.isna(x) or pd.isna(mid) or pd.isna(span) or denom == 0:
        return np.nan

    z = config.s_span * ((x - mid) / denom)
    score = config.rps_min + config.rps_range * _sigmoid(z)

    if config.clip_scores:
        score = np.clip(score, config.rps_min, config.rps_max)

    return float(score)


def _assign_attempt_weight(attempt_count: int, recency_rank: int) -> float:
    """
    Recency weighting for attempts within the same player and assessment.

    1 attempt:
        rank 1 = 1.00
    2 attempts:
        rank 1 = 2/3, rank 2 = 1/3
    3+ attempts:
        rank 1 = 0.50, rank 2 = 0.30, rank 3 = 0.20
        older attempts = 0
    """
    if recency_rank > 3:
        return 0.0

    if attempt_count == 1:
        return 1.0

    if attempt_count == 2:
        return 2 / 3 if recency_rank == 1 else 1 / 3

    if recency_rank == 1:
        return 0.50
    if recency_rank == 2:
        return 0.30
    if recency_rank == 3:
        return 0.20

    return 0.0


# ============================================================
# 5. PARAMETER TABLES
# ============================================================

def _build_global_params(
    data: pd.DataFrame,
    skill_col: str,
    span_percentile: float,
) -> pd.DataFrame:
    """Build global benchmark parameters by assessment."""
    return (
        data.groupby(skill_col)
        .agg(
            global_n=("score_oriented", "size"),
            global_mid=("score_oriented", "median"),
            global_span=("score_oriented", lambda x: x.quantile(span_percentile)),
            global_p25=("score_oriented", lambda x: x.quantile(0.25)),
            global_p75=("score_oriented", lambda x: x.quantile(0.75)),
            skill_type=("skill_type", "first"),
            good_direction=("good_direction", "first"),
        )
        .reset_index()
    )


def _build_cohort_params(
    data: pd.DataFrame,
    skill_col: str,
    cohort_col: str,
    span_percentile: float,
) -> pd.DataFrame:
    """Build age + gender cohort benchmark parameters by assessment and cohort."""
    return (
        data.groupby([skill_col, cohort_col])
        .agg(
            cohort_n=("score_oriented", "size"),
            cohort_mid=("score_oriented", "median"),
            cohort_span=("score_oriented", lambda x: x.quantile(span_percentile)),
            cohort_p25=("score_oriented", lambda x: x.quantile(0.25)),
            cohort_p75=("score_oriented", lambda x: x.quantile(0.75)),
        )
        .reset_index()
    )


def _build_age_group_params(
    data: pd.DataFrame,
    skill_col: str,
    age_group_col: str,
    span_percentile: float,
) -> pd.DataFrame:
    """
    Build age-only benchmark parameters by assessment and age group.
    This is the small-sample fallback that combines gender within the same age group.
    """
    return (
        data.groupby([skill_col, age_group_col])
        .agg(
            age_group_n=("score_oriented", "size"),
            age_group_mid=("score_oriented", "median"),
            age_group_span=("score_oriented", lambda x: x.quantile(span_percentile)),
            age_group_p25=("score_oriented", lambda x: x.quantile(0.25)),
            age_group_p75=("score_oriented", lambda x: x.quantile(0.75)),
        )
        .reset_index()
    )


# ============================================================
# 6. MAIN RPS SCORING FUNCTION
# ============================================================

def compare_global_vs_cohort_sigmoid_rps(
    df: pd.DataFrame,
    skill_col: str = "category_assessment",
    score_col: str = "score",
    cohort_col: str = "cohort",
    age_group_col: str = "age_group",
    gender_col: str = "gender_clean",
    timestamp_col: str = "timestamp",
    player_id_col: Optional[str] = None,
    span_percentile: float = 0.75,
    min_cohort_n: int = 30,
    skill_type_map: Optional[Dict[str, str]] = None,
    good_direction_map: Optional[Dict[str, str]] = None,
    clip_scores: bool = True,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, Dict[str, pd.DataFrame]]:
    """
    Calculate global and cohort-based RPS with age-group fallback for small cohorts.

    Small sample logic:
    1. If assessment + age + gender cohort has n >= min_cohort_n, use that cohort.
    2. If assessment + age + gender cohort has n < min_cohort_n, drop gender and use
       the same age group distribution for that assessment.
    3. If the age-group distribution is unavailable or invalid, use global as a safety fallback.
    """
    config = RPSConfig(
        span_percentile=span_percentile,
        min_cohort_n=min_cohort_n,
        clip_scores=clip_scores,
    )

    data = df.copy()

    required_cols = [
        skill_col,
        score_col,
        cohort_col,
        age_group_col,
        gender_col,
        timestamp_col,
    ]

    if player_id_col is not None:
        required_cols.append(player_id_col)
        player_cols = [player_id_col]
    else:
        required_cols.extend(["first_name", "last_name"])
        player_cols = ["first_name", "last_name", gender_col, age_group_col]

    _validate_columns(data, required_cols)

    data[score_col] = pd.to_numeric(data[score_col], errors="coerce")
    data[timestamp_col] = pd.to_datetime(data[timestamp_col], errors="coerce")

    data = data.dropna(
        subset=[skill_col, score_col, cohort_col, age_group_col, gender_col, timestamp_col]
    ).copy()

    if skill_type_map is None:
        skill_type_map = build_skill_type_map()

    if good_direction_map is None:
        good_direction_map = build_good_direction_map()

    # --------------------------------------------------------
    # Prepare modeling score
    # --------------------------------------------------------
    data["skill_type"] = data[skill_col].map(skill_type_map).fillna("Normal")
    data["good_direction"] = data[skill_col].map(good_direction_map).fillna("Hi")

    data["score_model"] = np.where(
        data["skill_type"].eq("Log"),
        data[score_col].apply(_safe_log),
        data[score_col],
    )

    data = data.dropna(subset=["score_model"]).copy()

    data["score_oriented"] = np.where(
        data["good_direction"].eq("Lo"),
        -data["score_model"],
        data["score_model"],
    )

    # --------------------------------------------------------
    # Build benchmark parameter tables
    # --------------------------------------------------------
    global_params = _build_global_params(data, skill_col, config.span_percentile)
    cohort_params = _build_cohort_params(data, skill_col, cohort_col, config.span_percentile)
    age_group_params = _build_age_group_params(
        data, skill_col, age_group_col, config.span_percentile
    )

    # --------------------------------------------------------
    # Merge benchmark parameters
    # --------------------------------------------------------
    result_df = data.merge(
        global_params[[skill_col, "global_n", "global_mid", "global_span"]],
        on=skill_col,
        how="left",
    )

    result_df = result_df.merge(
        cohort_params[
            [
                skill_col,
                cohort_col,
                "cohort_n",
                "cohort_mid",
                "cohort_span",
                "cohort_p25",
                "cohort_p75",
            ]
        ],
        on=[skill_col, cohort_col],
        how="left",
    )

    result_df = result_df.merge(
        age_group_params[
            [
                skill_col,
                age_group_col,
                "age_group_n",
                "age_group_mid",
                "age_group_span",
                "age_group_p25",
                "age_group_p75",
            ]
        ],
        on=[skill_col, age_group_col],
        how="left",
    )

    # --------------------------------------------------------
    # Select final benchmark source
    # --------------------------------------------------------
    result_df["cohort_is_small"] = result_df["cohort_n"] < config.min_cohort_n

    use_age_gender = result_df["cohort_n"] >= config.min_cohort_n

    result_df["rps_benchmark_source"] = np.where(
        use_age_gender,
        "age_gender_cohort",
        "same_age_group_gender_combined",
    )

    result_df["rps_mid"] = np.where(
        use_age_gender,
        result_df["cohort_mid"],
        result_df["age_group_mid"],
    )

    result_df["rps_span"] = np.where(
        use_age_gender,
        result_df["cohort_span"],
        result_df["age_group_span"],
    )

    invalid_final_benchmark = (
        result_df["rps_mid"].isna()
        | result_df["rps_span"].isna()
        | (result_df["rps_mid"] == result_df["rps_span"])
    )

    result_df.loc[invalid_final_benchmark, "rps_benchmark_source"] = "global_fallback"
    result_df.loc[invalid_final_benchmark, "rps_mid"] = result_df.loc[
        invalid_final_benchmark, "global_mid"
    ]
    result_df.loc[invalid_final_benchmark, "rps_span"] = result_df.loc[
        invalid_final_benchmark, "global_span"
    ]

    # --------------------------------------------------------
    # Calculate attempt-level RPS
    # --------------------------------------------------------
    result_df["rps_global_sigmoid"] = result_df.apply(
        lambda row: _calculate_sigmoid_rps(
            row["score_oriented"], row["global_mid"], row["global_span"], config
        ),
        axis=1,
    )

    result_df["rps_cohort_sigmoid"] = result_df.apply(
        lambda row: _calculate_sigmoid_rps(
            row["score_oriented"], row["rps_mid"], row["rps_span"], config
        ),
        axis=1,
    )

    result_df["rps_difference"] = (
        result_df["rps_cohort_sigmoid"] - result_df["rps_global_sigmoid"]
    )
    result_df["abs_rps_difference"] = result_df["rps_difference"].abs()

    # --------------------------------------------------------
    # Calculate recency-weighted assessment-level RPS
    # --------------------------------------------------------
    result_df = result_df.sort_values(
        player_cols + [skill_col, timestamp_col],
        ascending=[True] * (len(player_cols) + 1) + [False],
    ).copy()

    result_df["attempt_count"] = result_df.groupby(player_cols + [skill_col])[
        skill_col
    ].transform("size")

    result_df["attempt_recency_rank"] = (
        result_df.groupby(player_cols + [skill_col]).cumcount() + 1
    )

    result_df["use_for_overall_rps"] = result_df["attempt_recency_rank"] <= 3

    result_df["attempt_weight"] = result_df.apply(
        lambda row: _assign_attempt_weight(
            int(row["attempt_count"]), int(row["attempt_recency_rank"])
        ),
        axis=1,
    )

    result_df["weighted_global_rps"] = (
        result_df["rps_global_sigmoid"] * result_df["attempt_weight"]
    )
    result_df["weighted_cohort_rps"] = (
        result_df["rps_cohort_sigmoid"] * result_df["attempt_weight"]
    )

    player_assessment_rps = (
        result_df[result_df["use_for_overall_rps"]]
        .groupby(player_cols + [skill_col], as_index=False)
        .agg(
            assessment_global_rps=("weighted_global_rps", "sum"),
            assessment_cohort_rps=("weighted_cohort_rps", "sum"),
            attempts_used_for_rps=("attempt_recency_rank", "max"),
            total_attempts=("attempt_count", "max"),
            most_recent_timestamp=(timestamp_col, "max"),
            benchmark_source=("rps_benchmark_source", "first"),
            cohort_n=("cohort_n", "first"),
            age_group_n=("age_group_n", "first"),
        )
    )

    # --------------------------------------------------------
    # Calculate overall player RPS
    # --------------------------------------------------------
    overall_player_rps = (
        player_assessment_rps.groupby(player_cols, as_index=False)
        .agg(
            overall_global_rps=("assessment_global_rps", "mean"),
            overall_cohort_rps=("assessment_cohort_rps", "mean"),
            number_of_assessments=(skill_col, "nunique"),
        )
    )

    overall_player_rps["overall_rps_difference"] = (
        overall_player_rps["overall_cohort_rps"]
        - overall_player_rps["overall_global_rps"]
    )

    diagnostics = _build_diagnostics(
        result_df=result_df,
        cohort_params=cohort_params,
        age_group_params=age_group_params,
        player_assessment_rps=player_assessment_rps,
        overall_player_rps=overall_player_rps,
        skill_col=skill_col,
        score_col=score_col,
        cohort_col=cohort_col,
        age_group_col=age_group_col,
        gender_col=gender_col,
        timestamp_col=timestamp_col,
        player_cols=player_cols,
    )

    return result_df, global_params, cohort_params, age_group_params, diagnostics


# ============================================================
# 7. DIAGNOSTICS
# ============================================================

def _safe_corr(df: pd.DataFrame, col_a: str, col_b: str) -> float:
    """Return correlation safely when enough non-missing data exists."""
    temp = df[[col_a, col_b]].dropna()
    if len(temp) < 2:
        return np.nan
    return float(temp.corr().iloc[0, 1])


def _build_diagnostics(
    result_df: pd.DataFrame,
    cohort_params: pd.DataFrame,
    age_group_params: pd.DataFrame,
    player_assessment_rps: pd.DataFrame,
    overall_player_rps: pd.DataFrame,
    skill_col: str,
    score_col: str,
    cohort_col: str,
    age_group_col: str,
    gender_col: str,
    timestamp_col: str,
    player_cols: List[str],
) -> Dict[str, pd.DataFrame]:
    """Build diagnostic tables used to validate scoring behavior."""

    overall_comparison = pd.DataFrame(
        {
            "metric": [
                "number_of_records",
                "number_of_skills",
                "number_of_cohorts",
                "avg_global_rps",
                "avg_cohort_rps",
                "avg_difference",
                "median_difference",
                "avg_absolute_difference",
                "correlation_global_vs_cohort",
                "pct_records_diff_gt_5",
                "pct_records_diff_gt_10",
                "pct_small_cohort_records",
                "pct_age_gender_source",
                "pct_age_group_fallback_source",
                "pct_global_fallback_source",
                "avg_overall_global_rps",
                "avg_overall_cohort_rps",
            ],
            "value": [
                len(result_df),
                result_df[skill_col].nunique(),
                result_df[cohort_col].nunique(),
                result_df["rps_global_sigmoid"].mean(),
                result_df["rps_cohort_sigmoid"].mean(),
                result_df["rps_difference"].mean(),
                result_df["rps_difference"].median(),
                result_df["abs_rps_difference"].mean(),
                _safe_corr(result_df, "rps_global_sigmoid", "rps_cohort_sigmoid"),
                (result_df["abs_rps_difference"] > 5).mean(),
                (result_df["abs_rps_difference"] > 10).mean(),
                result_df["cohort_is_small"].mean(),
                result_df["rps_benchmark_source"].eq("age_gender_cohort").mean(),
                result_df["rps_benchmark_source"]
                .eq("same_age_group_gender_combined")
                .mean(),
                result_df["rps_benchmark_source"].eq("global_fallback").mean(),
                overall_player_rps["overall_global_rps"].mean(),
                overall_player_rps["overall_cohort_rps"].mean(),
            ],
        }
    )

    skill_comparison = (
        result_df.groupby(skill_col)
        .agg(
            n=(score_col, "size"),
            global_rps_mean=("rps_global_sigmoid", "mean"),
            cohort_rps_mean=("rps_cohort_sigmoid", "mean"),
            avg_difference=("rps_difference", "mean"),
            median_difference=("rps_difference", "median"),
            avg_abs_difference=("abs_rps_difference", "mean"),
            pct_diff_gt_5=("abs_rps_difference", lambda x: (x > 5).mean()),
            pct_diff_gt_10=("abs_rps_difference", lambda x: (x > 10).mean()),
            min_cohort_n=("cohort_n", "min"),
            max_cohort_n=("cohort_n", "max"),
            min_age_group_n=("age_group_n", "min"),
            max_age_group_n=("age_group_n", "max"),
        )
        .reset_index()
        .sort_values("avg_abs_difference", ascending=False)
    )

    cohort_comparison = (
        result_df.groupby(cohort_col)
        .agg(
            n=(score_col, "size"),
            global_rps_mean=("rps_global_sigmoid", "mean"),
            cohort_rps_mean=("rps_cohort_sigmoid", "mean"),
            avg_difference=("rps_difference", "mean"),
            median_difference=("rps_difference", "median"),
            avg_abs_difference=("abs_rps_difference", "mean"),
            pct_diff_gt_5=("abs_rps_difference", lambda x: (x > 5).mean()),
            pct_diff_gt_10=("abs_rps_difference", lambda x: (x > 10).mean()),
            pct_age_group_fallback=(
                "rps_benchmark_source",
                lambda x: x.eq("same_age_group_gender_combined").mean(),
            ),
            pct_global_fallback=(
                "rps_benchmark_source",
                lambda x: x.eq("global_fallback").mean(),
            ),
        )
        .reset_index()
        .sort_values("avg_abs_difference", ascending=False)
    )

    stability_table = (
        result_df.groupby([skill_col, cohort_col, age_group_col], as_index=False)
        .agg(
            cohort_n=("cohort_n", "first"),
            age_group_n=("age_group_n", "first"),
            benchmark_source=("rps_benchmark_source", "first"),
            cohort_mid=("cohort_mid", "first"),
            cohort_span=("cohort_span", "first"),
            age_group_mid=("age_group_mid", "first"),
            age_group_span=("age_group_span", "first"),
            final_mid=("rps_mid", "first"),
            final_span=("rps_span", "first"),
        )
        .sort_values(["benchmark_source", "cohort_n"], ascending=[True, True])
    )

    largest_changes = (
        result_df.sort_values("abs_rps_difference", ascending=False)[
            player_cols
            + [
                skill_col,
                cohort_col,
                age_group_col,
                gender_col,
                score_col,
                timestamp_col,
                "skill_type",
                "good_direction",
                "cohort_n",
                "age_group_n",
                "rps_benchmark_source",
                "rps_global_sigmoid",
                "rps_cohort_sigmoid",
                "rps_difference",
                "abs_rps_difference",
            ]
        ].head(50)
    )

    monotonicity_check = _build_monotonicity_check(
        result_df=result_df,
        skill_col=skill_col,
        cohort_col=cohort_col,
    )

    return {
        "overall_comparison": overall_comparison,
        "skill_comparison": skill_comparison,
        "cohort_comparison": cohort_comparison,
        "stability_table": stability_table,
        "largest_changes": largest_changes,
        "monotonicity_check": monotonicity_check,
        "player_assessment_rps": player_assessment_rps,
        "overall_player_rps": overall_player_rps,
        "cohort_params": cohort_params,
        "age_group_params": age_group_params,
    }


def _build_monotonicity_check(
    result_df: pd.DataFrame,
    skill_col: str,
    cohort_col: str,
) -> pd.DataFrame:
    """Check whether RPS decreases when oriented score increases."""
    monotonicity_issues = []

    for skill, temp in result_df.groupby(skill_col):
        temp = temp.sort_values("score_oriented")

        global_diff = temp["rps_global_sigmoid"].diff().dropna()
        if (global_diff < -1e-8).any():
            monotonicity_issues.append(
                {
                    "skill": skill,
                    "system": "global",
                    "issue": "RPS decreases when oriented score increases",
                }
            )

        for source_group, ctemp in temp.groupby([cohort_col, "rps_benchmark_source"]):
            cohort_diff = ctemp["rps_cohort_sigmoid"].diff().dropna()
            if (cohort_diff < -1e-8).any():
                monotonicity_issues.append(
                    {
                        "skill": skill,
                        "group": source_group,
                        "system": "cohort",
                        "issue": "RPS decreases within benchmark group when oriented score increases",
                    }
                )

    return pd.DataFrame(monotonicity_issues)


# ============================================================
# 8. CONVENIENCE RUNNER
# ============================================================

def run_rps_pipeline(
    file_name: str = "training_session.csv",
    player_id_col: Optional[str] = None,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, Dict[str, pd.DataFrame]]:
    """
    Load, preprocess, and score the training data.
    """
    raw_df = load_training_data(file_name)
    df = preprocess_training_data(raw_df)

    skill_type_map = build_skill_type_map()
    good_direction_map = build_good_direction_map()

    return compare_global_vs_cohort_sigmoid_rps(
        df,
        skill_col="category_assessment",
        score_col="score",
        cohort_col="cohort",
        age_group_col="age_group",
        gender_col="gender_clean",
        timestamp_col="timestamp",
        player_id_col=player_id_col,
        span_percentile=0.75,
        min_cohort_n=30,
        skill_type_map=skill_type_map,
        good_direction_map=good_direction_map,
    )


# ============================================================
# 9. EXAMPLE USAGE
# ============================================================

if __name__ == "__main__":
    result_df, global_params, cohort_params, age_group_params, diagnostics = run_rps_pipeline(
        file_name="training_session.csv",
        player_id_col=None,
    )

    print("Pipeline completed.")
    print("Result rows:", len(result_df))
    print("Diagnostics tables:", list(diagnostics.keys()))
    print("\nOverall comparison:")
    print(diagnostics["overall_comparison"])

diagnostics['overall_player_rps']

player_first = 'Abby'
player_last = 'Foulk'
assessment = 'Freelap 10yd Dash Ball'

# Filter the main detailed result dataframe
abby_calc = result_df[
    (result_df['first_name'] == player_first) &
    (result_df['last_name'] == player_last) &
    (result_df['category_assessment'] == assessment)
]

# Select the columns that show the step-by-step calculation
calc_cols = [
    'timestamp', 'score', 'score_model', 'score_oriented',
    'rps_benchmark_source', 'cohort_n', 'age_group_n',
    'global_mid', 'global_span', 'rps_mid', 'rps_span',
    'rps_global_sigmoid', 'rps_cohort_sigmoid', 'attempt_weight'
]

display(abby_calc[calc_cols])

