# -*- coding: utf-8 -*-
"""final_aps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XNI1mQrnGHG6LrYYGhHoeLDt4Vo1WMD-
"""

# -*- coding: utf-8 -*-
"""
APS Scoring System
==================

This script builds the Absolute Performance Score (APS) system for Sogility data.

Core logic
----------
1. Load and preprocess raw training session data.
2. Create age groups, clean gender, and define age-gender cohorts.
3. Exclude unmapped assessments from scoring, while keeping an audit table.
4. Build APS benchmarks using each player's most recent attempt per assessment.
5. Handle small cohort sample sizes by dropping gender and combining within age group.
6. Score every valid raw attempt using APS benchmark interpolation.
7. Calculate recency-weighted assessment APS.
8. Calculate category-level APS.
9. Calculate final overall APS.
10. Return dashboard-ready tables and diagnostics.

Important
---------
Log transformations are applied inside preprocessing. Do not apply them before running
this script unless you intentionally remove the log-transform step here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


# ============================================================
# 1. CONFIGURATION
# ============================================================


@dataclass
class APSConfig:
    """Configuration for APS scoring."""

    file_name: str = "training_session.csv"
    min_cohort_n: int = 30
    aps_score_col: str = "APS"

    raw_columns: List[str] = field(
        default_factory=lambda: [
            "first_name",
            "last_name",
            "gender",
            "col_d",
            "category",
            "assessment",
            "score",
            "timestamp",
        ]
    )

    age_map: Dict[str, int] = field(
        default_factory=lambda: {
            "A": 1,
            "B": 1,
            "C": 2,
            "D": 2,
            "E": 3,
            "F": 3,
        }
    )

    higher_is_better_map: Dict[str, bool] = field(
        default_factory=lambda: {
            # Lower is better
            "Broad Jump 5-10-5 Shuttles": False,
            "Circuit Training Knockout": False,
            "Circuit Training Knockout-Obstacle": False,
            "Freelap 10yd Dash": False,
            "Freelap 10yd Dash Ball": False,
            "Freelap 20yd Dash": False,
            "Freelap 20yd Dash Ball": False,
            "RoxPro 5-10-5 shuttle": False,
            "RoxPro Sprint-10 yrd": False,
            # Higher is better
            "Broad Jump Horizontal": True,
            "Circuit Training Maestro": True,
            "Circuit Training Pass Find 1": True,
            "Circuit Training Vision": True,
            "Fast Feet Architect": True,
            "Fast Feet Maestro": True,
            "Fast Feet Vision": True,
            "ICON 4M Architect": True,
            "ICON 4M Maestro": True,
            "ICON 4M Vision": True,
            "ICON Q Pass Find 2": True,
            "ICON V2 Architect": True,
            "ICON V2 Maestro": True,
            "ICON V2 Vision": True,
            "Reflexion Edge Hand Eye Coordination": True,
            "Reflexion Edge Inhibition": True,
            "Reflexion Edge Prioritization": True,
            "Reflexion Edge Reaction Time": True,
            "Reflexion Edge Tracking": True,
            "Tech Touch Ground & Tech Touch Air Receive 10 Air": True,
            "Tech Touch Ground & Tech Touch Air Receive 10 Ground": True,
            "Tech Touch One Touch Pass Pass 10 Air": True,
            "Tech Touch One Touch Pass Pass 10 Ground": True,
            "Vertical Jump Vertical": True,
            # Assessments from newer data
            "Circuit Maestro": True,
            "Circuit Vision": True,
            "Circuit Pass find 1": True,
            "ICON Q Pass find 2": True,
            "TechTouch 1st Touch - Air": True,
            "TechTouch 1st touch - ground": True,
            "Vision Wall GO 360": True,
            "Vision Wall Scan & React": True,
            "Vision Wall Large to Small": True,
            "Vision Wall Balance Reaction": True,
        }
    )

    log_transform_assessments: List[str] = field(
        default_factory=lambda: [
            "Circuit Training Knockout",
            "Circuit Training Knockout-Obstacle",
            "Freelap 10yd Dash",
            "Freelap 10yd Dash Ball",
            "Freelap 20yd Dash",
            "Freelap 20yd Dash Ball",
            "RoxPro 5-10-5 shuttle",
            "RoxPro Sprint-10 yrd",
        ]
    )

    benchmark_quantiles: List[float] = field(
        default_factory=lambda: [0.30, 0.50, 0.70, 0.90]
    )


# ============================================================
# 2. DATA LOADING AND PREPROCESSING
# ============================================================


def load_training_data(file_name: str, raw_columns: List[str]) -> pd.DataFrame:
    """Load raw training session data and assign expected columns."""
    df = pd.read_csv(file_name, header=None)

    if df.shape[1] != len(raw_columns):
        raise ValueError(
            f"Expected {len(raw_columns)} columns, but found {df.shape[1]} columns."
        )

    df.columns = raw_columns
    return df


def clean_basic_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Clean text columns, convert score and timestamp, and create category_assessment."""
    data = df.copy()

    data["score"] = pd.to_numeric(data["score"], errors="coerce")
    data["timestamp"] = pd.to_datetime(data["timestamp"], errors="coerce")

    text_cols = ["first_name", "last_name", "gender", "col_d", "category", "assessment"]
    for col in text_cols:
        data[col] = data[col].astype(str).str.strip()

    data["category_assessment"] = data["category"] + " " + data["assessment"]

    data = data.dropna(subset=["score", "timestamp", "category_assessment"]).copy()
    return data


def add_cohort_fields(df: pd.DataFrame, config: APSConfig) -> pd.DataFrame:
    """Create age_group, gender_clean, and cohort columns."""
    data = df.copy()

    data["age_group"] = data["col_d"].map(config.age_map)
    data["gender_clean"] = data["gender"].str.upper().str[0]

    data = data[
        data["age_group"].notna()
        & data["gender_clean"].isin(["M", "F"])
    ].copy()

    data["age_group"] = data["age_group"].astype("Int64")
    data["cohort"] = data["age_group"].astype(str) + "_" + data["gender_clean"]

    return data


def add_score_metadata(df: pd.DataFrame, config: APSConfig) -> pd.DataFrame:
    """Add higher_is_better and apply log transformation for configured assessments."""
    data = df.copy()

    data["higher_is_better"] = (
        data["category_assessment"]
        .map(config.higher_is_better_map)
        .fillna(True)
    )

    log_mask = data["category_assessment"].isin(config.log_transform_assessments)
    positive_mask = data["score"] > 0

    data.loc[log_mask & positive_mask, "score"] = np.log(
        pd.to_numeric(data.loc[log_mask & positive_mask, "score"], errors="coerce")
    )

    data.loc[log_mask & ~positive_mask, "score"] = np.nan
    data = data.dropna(subset=["score"]).copy()

    return data


def preprocess_training_data(df: pd.DataFrame, config: APSConfig) -> pd.DataFrame:
    """Run the full preprocessing pipeline."""
    data = clean_basic_columns(df)
    data = add_cohort_fields(data, config)
    data = add_score_metadata(data, config)
    return data


# ============================================================
# 3. APS SCORING HELPERS
# ============================================================


def get_player_cols(df: pd.DataFrame) -> List[str]:
    """Use athlete_id when available, otherwise fall back to name, gender, and age group."""
    if "athlete_id" in df.columns:
        return ["athlete_id"]
    return ["first_name", "last_name", "gender_clean", "age_group"]


def map_assessment_category(assessment: object) -> str:
    """Map each assessment to one APS parent category."""
    if pd.isna(assessment):
        return "Unmapped"

    a = str(assessment).lower()

    if "circuit" in a:
        return "Dribbling"

    if "icon" in a:
        return "Passing"

    if (
        "tech touch" in a
        or "techtouch" in a
        or "1st touch" in a
        or "one touch" in a
    ):
        return "First Touch"

    if (
        "5-10-5" in a
        or "shuttle" in a
        or "sprint" in a
        or "10yd" in a
        or "10 yd" in a
        or "10yrd" in a
        or "10 yrd" in a
        or "dash" in a
    ):
        return "Agility"

    if (
        "go 360" in a
        or "scan" in a
        or "react" in a
        or "reaction" in a
        or "large to small" in a
        or "small to large" in a
        or "balance" in a
        or "vision wall" in a
        or "roxpro" in a
        or "reflection edge" in a
    ):
        return "Vision"

    return "Unmapped"


def interpolate_score(x: float, x0: float, x1: float, y0: float, y1: float) -> float:
    """Linearly interpolate y for x between two benchmark anchors."""
    if pd.isna(x0) or pd.isna(x1) or x1 == x0:
        return np.nan
    return y0 + (x - x0) * (y1 - y0) / (x1 - x0)


def aps_from_benchmarks(
    score: float,
    q30: float,
    q50: float,
    q70: float,
    q90: float,
    higher_is_better: bool = True,
) -> float:
    """
    Convert raw score into APS using benchmark anchors.

    Anchors:
        q30 -> 30
        q50 -> 50
        q70 -> 70
        q90 -> 90
    """
    if any(pd.isna(v) for v in [score, q30, q50, q70, q90]):
        return np.nan

    if not higher_is_better:
        score = -score
        q30, q50, q70, q90 = sorted([-q90, -q70, -q50, -q30])

    if score <= q30:
        aps = interpolate_score(score, q30 - (q50 - q30), q30, 0, 30)
    elif score <= q50:
        aps = interpolate_score(score, q30, q50, 30, 50)
    elif score <= q70:
        aps = interpolate_score(score, q50, q70, 50, 70)
    elif score <= q90:
        aps = interpolate_score(score, q70, q90, 70, 90)
    else:
        aps = interpolate_score(score, q90, q90 + (q90 - q70), 90, 100)

    return float(np.clip(aps, 0, 100))


def assign_aps_band(score: float) -> object:
    """Convert APS score into a performance band."""
    if pd.isna(score):
        return np.nan
    if score < 30:
        return "Foundation"
    if score < 50:
        return "Developing"
    if score < 70:
        return "Approaching"
    if score < 90:
        return "Strong"
    return "Elite"


def get_recent_weights(n: int) -> List[float]:
    """Return recency weights for the most recent one, two, or three attempts."""
    if n == 1:
        return [1.0]
    if n == 2:
        return [2 / 3, 1 / 3]
    return [0.5, 0.3, 0.2]


def weighted_recent_assessment_score(group: pd.DataFrame) -> pd.Series:
    """Calculate weighted APS for one player and one assessment."""
    recent = group.sort_values("timestamp", ascending=False).head(3).copy()
    weights = get_recent_weights(len(recent))

    recent["recent_weight"] = weights
    weighted_score = np.average(recent["APS"], weights=recent["recent_weight"])

    return pd.Series(
        {
            "weighted_assessment_aps": weighted_score,
            "individual_assessment_band": assign_aps_band(weighted_score),
            "n_recent_scores_used": len(recent),
            "latest_assessment_date": recent["timestamp"].max(),
            "weights_used": ", ".join(str(round(w, 3)) for w in weights),
            "raw_attempt_aps_used": ", ".join(
                str(round(v, 1)) for v in recent["APS"]
            ),
        }
    )


# ============================================================
# 4. BENCHMARK CONSTRUCTION
# ============================================================


def prepare_scoring_input(df: pd.DataFrame) -> pd.DataFrame:
    """Add APS category and exclude unmapped assessments from scoring input."""
    data = df.copy()
    data["aps_category"] = data["category_assessment"].apply(map_assessment_category)

    scoring_input = (
        data.dropna(subset=["score", "timestamp", "category_assessment", "cohort", "age_group"])
        .query("aps_category != 'Unmapped'")
        .copy()
    )

    return scoring_input


def build_benchmark_base(
    scoring_input: pd.DataFrame,
    player_cols: List[str],
    min_cohort_n: int,
) -> pd.DataFrame:
    """
    Build benchmark base using each player's most recent attempt per assessment.

    Small sample logic:
        If age-gender cohort has fewer than min_cohort_n players, use same age group
        across gender as the benchmark cohort.
    """
    benchmark_base = (
        scoring_input.sort_values("timestamp")
        .drop_duplicates(subset=player_cols + ["category_assessment"], keep="last")
        .copy()
    )

    cohort_sizes = (
        benchmark_base.groupby(["category_assessment", "cohort"])
        .size()
        .reset_index(name="n_original_cohort")
    )

    benchmark_base = benchmark_base.merge(
        cohort_sizes,
        on=["category_assessment", "cohort"],
        how="left",
    )

    benchmark_base["combined_for_small_sample"] = (
        benchmark_base["n_original_cohort"] < min_cohort_n
    )

    benchmark_base["benchmark_type"] = np.where(
        benchmark_base["combined_for_small_sample"],
        "age_group",
        "age_gender",
    )

    benchmark_base["aps_distribution_used"] = np.where(
        benchmark_base["combined_for_small_sample"],
        "Combined with same age group across gender",
        "Original age-gender cohort",
    )

    benchmark_base["benchmark_cohort"] = np.where(
        benchmark_base["benchmark_type"] == "age_group",
        benchmark_base["age_group"].astype(str),
        benchmark_base["cohort"],
    )

    return benchmark_base


def build_benchmark_source(benchmark_base: pd.DataFrame) -> pd.DataFrame:
    """Create both age-gender and age-only benchmark distributions."""
    age_gender_source = benchmark_base.copy()
    age_gender_source["benchmark_cohort"] = age_gender_source["cohort"]

    age_source = benchmark_base.copy()
    age_source["benchmark_cohort"] = age_source["age_group"].astype(str)

    return pd.concat([age_gender_source, age_source], ignore_index=True)


def build_benchmark_table(
    benchmark_source: pd.DataFrame,
    benchmark_quantiles: List[float],
) -> pd.DataFrame:
    """Build benchmark quantile table and sample sizes."""
    benchmark_table = (
        benchmark_source.groupby(["category_assessment", "benchmark_cohort"])["score"]
        .quantile(benchmark_quantiles)
        .unstack()
        .reset_index()
    )

    benchmark_table.columns = [
        "category_assessment",
        "benchmark_cohort",
        "q30",
        "q50",
        "q70",
        "q90",
    ]

    benchmark_sample_sizes = (
        benchmark_source.groupby(["category_assessment", "benchmark_cohort"])
        .size()
        .reset_index(name="n_benchmark_distribution")
    )

    benchmark_table = benchmark_table.merge(
        benchmark_sample_sizes,
        on=["category_assessment", "benchmark_cohort"],
        how="left",
    )

    return benchmark_table


def merge_benchmarks_to_attempts(
    scoring_input: pd.DataFrame,
    benchmark_base: pd.DataFrame,
    benchmark_table: pd.DataFrame,
    player_cols: List[str],
) -> pd.DataFrame:
    """Attach benchmark metadata and quantiles to every valid scoring attempt."""
    benchmark_lookup_cols = player_cols + [
        "category_assessment",
        "n_original_cohort",
        "combined_for_small_sample",
        "benchmark_type",
        "aps_distribution_used",
        "benchmark_cohort",
    ]

    benchmark_lookup = benchmark_base[benchmark_lookup_cols].drop_duplicates()

    scoring_df = scoring_input.merge(
        benchmark_lookup,
        on=player_cols + ["category_assessment"],
        how="left",
    )

    scoring_df = scoring_df.merge(
        benchmark_table,
        on=["category_assessment", "benchmark_cohort"],
        how="left",
    )

    return scoring_df


# ============================================================
# 5. APS CALCULATION PIPELINE
# ============================================================


def calculate_attempt_aps(scoring_df: pd.DataFrame) -> pd.DataFrame:
    """Calculate APS and attempt-level APS band for each raw attempt."""
    data = scoring_df.copy()

    data["APS"] = data.apply(
        lambda row: aps_from_benchmarks(
            score=row["score"],
            q30=row["q30"],
            q50=row["q50"],
            q70=row["q70"],
            q90=row["q90"],
            higher_is_better=row["higher_is_better"],
        ),
        axis=1,
    )

    data["APS_band_raw_attempt"] = data["APS"].apply(assign_aps_band)
    return data


def calculate_assessment_scores(
    scoring_df: pd.DataFrame,
    player_cols: List[str],
) -> pd.DataFrame:
    """Calculate recency-weighted APS for each player-assessment."""
    valid_scores = (
        scoring_df.dropna(subset=["APS", "aps_category", "timestamp"])
        .query("aps_category != 'Unmapped'")
        .copy()
    )

    assessment_recent_scores = (
        valid_scores.groupby(
            player_cols + ["aps_category", "category_assessment"],
            as_index=False,
        )
        .apply(weighted_recent_assessment_score)
        .reset_index(drop=True)
    )

    assessment_recent_scores["weighted_assessment_aps"] = (
        assessment_recent_scores["weighted_assessment_aps"].round(1)
    )

    return assessment_recent_scores


def calculate_category_scores(
    assessment_recent_scores: pd.DataFrame,
    player_cols: List[str],
) -> pd.DataFrame:
    """Average weighted assessment APS scores into APS parent categories."""
    category_scores = (
        assessment_recent_scores.groupby(player_cols + ["aps_category"], as_index=False)
        .agg(
            category_aps_score=("weighted_assessment_aps", "mean"),
            n_assessments_used=("category_assessment", "nunique"),
            assessments_used=(
                "category_assessment",
                lambda x: ", ".join(sorted(x.dropna().unique())),
            ),
        )
    )

    category_scores["category_aps_score"] = category_scores["category_aps_score"].round(1)
    category_scores["category_aps_band"] = category_scores["category_aps_score"].apply(assign_aps_band)

    return category_scores


def calculate_final_aps(
    category_scores: pd.DataFrame,
    player_cols: List[str],
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Calculate final overall APS and dashboard-friendly wide table."""
    final_aps = (
        category_scores.groupby(player_cols, as_index=False)
        .agg(
            final_aps_score=("category_aps_score", "mean"),
            n_categories_used=("aps_category", "nunique"),
        )
    )

    final_aps["final_aps_score"] = final_aps["final_aps_score"].round(1)
    final_aps["final_aps_band"] = final_aps["final_aps_score"].apply(assign_aps_band)

    category_scores_wide = category_scores.pivot_table(
        index=player_cols,
        columns="aps_category",
        values="category_aps_score",
        aggfunc="mean",
    ).reset_index()

    final_dashboard_scores = final_aps.merge(
        category_scores_wide,
        on=player_cols,
        how="left",
    )

    return final_aps, final_dashboard_scores


# ============================================================
# 6. DIAGNOSTICS
# ============================================================


def build_diagnostics(
    raw_df: pd.DataFrame,
    scoring_df: pd.DataFrame,
    benchmark_base: pd.DataFrame,
    benchmark_table: pd.DataFrame,
    assessment_recent_scores: pd.DataFrame,
    category_scores: pd.DataFrame,
    final_aps: pd.DataFrame,
    final_dashboard_scores: pd.DataFrame,
    player_cols: List[str],
) -> Dict[str, pd.DataFrame]:
    """Build all APS diagnostics and audit tables."""

    unmapped_rows = (raw_df["aps_category"] == "Unmapped").sum()

    overall_summary = pd.DataFrame(
        {
            "metric": [
                "total_raw_rows",
                "rows_used_for_scoring",
                "unmapped_rows_excluded",
                "unique_players_scored",
                "unique_assessments_scored",
                "unique_categories_scored",
                "mean_final_aps",
                "median_final_aps",
                "min_final_aps",
                "max_final_aps",
            ],
            "value": [
                len(raw_df),
                len(scoring_df),
                unmapped_rows,
                final_aps[player_cols].drop_duplicates().shape[0],
                assessment_recent_scores["category_assessment"].nunique(),
                category_scores["aps_category"].nunique(),
                final_aps["final_aps_score"].mean(),
                final_aps["final_aps_score"].median(),
                final_aps["final_aps_score"].min(),
                final_aps["final_aps_score"].max(),
            ],
        }
    )

    assessment_diagnostics = (
        assessment_recent_scores.groupby(["aps_category", "category_assessment"], as_index=False)
        .agg(
            n_players=("weighted_assessment_aps", "count"),
            mean_weighted_aps=("weighted_assessment_aps", "mean"),
            median_weighted_aps=("weighted_assessment_aps", "median"),
            min_weighted_aps=("weighted_assessment_aps", "min"),
            max_weighted_aps=("weighted_assessment_aps", "max"),
            avg_recent_scores_used=("n_recent_scores_used", "mean"),
        )
        .round(2)
    )

    category_diagnostics = (
        category_scores.groupby("aps_category", as_index=False)
        .agg(
            n_players=("category_aps_score", "count"),
            mean_category_aps=("category_aps_score", "mean"),
            median_category_aps=("category_aps_score", "median"),
            min_category_aps=("category_aps_score", "min"),
            max_category_aps=("category_aps_score", "max"),
            avg_assessments_used=("n_assessments_used", "mean"),
        )
        .round(2)
    )

    cohort_diagnostics = (
        benchmark_base.groupby(
            ["category_assessment", "cohort", "benchmark_type", "benchmark_cohort"],
            as_index=False,
        )
        .agg(
            n_original_cohort=("n_original_cohort", "max"),
            combined_for_small_sample=("combined_for_small_sample", "max"),
        )
        .sort_values(["category_assessment", "cohort"])
    )

    small_sample_diagnostics = (
        benchmark_base[
            [
                "category_assessment",
                "cohort",
                "age_group",
                "n_original_cohort",
                "combined_for_small_sample",
                "benchmark_type",
                "benchmark_cohort",
                "aps_distribution_used",
            ]
        ]
        .drop_duplicates()
        .sort_values(
            ["combined_for_small_sample", "category_assessment", "cohort"],
            ascending=[False, True, True],
        )
    )

    assessment_band_distribution = (
        assessment_recent_scores.groupby(
            ["aps_category", "category_assessment", "individual_assessment_band"],
            as_index=False,
        )
        .size()
        .rename(columns={"size": "n_players"})
    )

    category_band_distribution = (
        category_scores.groupby(["aps_category", "category_aps_band"], as_index=False)
        .size()
        .rename(columns={"size": "n_players"})
    )

    final_band_distribution = (
        final_aps.groupby("final_aps_band", as_index=False)
        .size()
        .rename(columns={"size": "n_players"})
    )

    recent_weighting_diagnostics = (
        assessment_recent_scores.groupby(["n_recent_scores_used", "weights_used"], as_index=False)
        .size()
        .rename(columns={"size": "n_player_assessments"})
        .sort_values("n_recent_scores_used")
    )

    unmapped_diagnostics = (
        raw_df[raw_df["aps_category"] == "Unmapped"]["category_assessment"]
        .value_counts()
        .reset_index()
    )
    unmapped_diagnostics.columns = ["category_assessment", "excluded_count"]

    benchmark_problem_diagnostics = benchmark_table[
        benchmark_table[["q30", "q50", "q70", "q90"]].isna().any(axis=1)
    ].copy()

    monotonicity_check = benchmark_table.copy()
    monotonicity_check["is_monotonic"] = (
        (monotonicity_check["q30"] <= monotonicity_check["q50"])
        & (monotonicity_check["q50"] <= monotonicity_check["q70"])
        & (monotonicity_check["q70"] <= monotonicity_check["q90"])
    )
    monotonicity_check = monotonicity_check[monotonicity_check["is_monotonic"] == False]

    return {
        "overall_summary": overall_summary,
        "assessment_diagnostics": assessment_diagnostics,
        "category_diagnostics": category_diagnostics,
        "cohort_diagnostics": cohort_diagnostics,
        "small_sample_diagnostics": small_sample_diagnostics,
        "assessment_band_distribution": assessment_band_distribution,
        "category_band_distribution": category_band_distribution,
        "final_band_distribution": final_band_distribution,
        "recent_weighting_diagnostics": recent_weighting_diagnostics,
        "player_assessment_aps": assessment_recent_scores.copy(),
        "overall_player_aps": final_dashboard_scores.copy(),
        "unmapped_diagnostics": unmapped_diagnostics,
        "benchmark_problem_diagnostics": benchmark_problem_diagnostics,
        "monotonicity_check": monotonicity_check,
    }


# ============================================================
# 7. MAIN ORCHESTRATOR
# ============================================================


def run_aps_scoring(
    df: Optional[pd.DataFrame] = None,
    config: Optional[APSConfig] = None,
) -> Dict[str, object]:
    """
    Run full APS scoring pipeline.

    Returns a dictionary containing:
        df
        scoring_input
        benchmark_base
        benchmark_source
        benchmark_table
        scoring_df
        assessment_recent_scores
        category_scores
        final_aps
        final_dashboard_scores
        diagnostics
        player_cols
    """
    config = config or APSConfig()

    if df is None:
        raw_df = load_training_data(config.file_name, config.raw_columns)
    else:
        raw_df = df.copy()

    processed_df = preprocess_training_data(raw_df, config)
    player_cols = get_player_cols(processed_df)

    processed_df["aps_category"] = processed_df["category_assessment"].apply(map_assessment_category)
    scoring_input = prepare_scoring_input(processed_df)

    benchmark_base = build_benchmark_base(
        scoring_input=scoring_input,
        player_cols=player_cols,
        min_cohort_n=config.min_cohort_n,
    )

    benchmark_source = build_benchmark_source(benchmark_base)
    benchmark_table = build_benchmark_table(
        benchmark_source=benchmark_source,
        benchmark_quantiles=config.benchmark_quantiles,
    )

    scoring_df = merge_benchmarks_to_attempts(
        scoring_input=scoring_input,
        benchmark_base=benchmark_base,
        benchmark_table=benchmark_table,
        player_cols=player_cols,
    )

    scoring_df = calculate_attempt_aps(scoring_df)
    assessment_recent_scores = calculate_assessment_scores(scoring_df, player_cols)
    category_scores = calculate_category_scores(assessment_recent_scores, player_cols)
    final_aps, final_dashboard_scores = calculate_final_aps(category_scores, player_cols)

    diagnostics = build_diagnostics(
        raw_df=processed_df,
        scoring_df=scoring_df,
        benchmark_base=benchmark_base,
        benchmark_table=benchmark_table,
        assessment_recent_scores=assessment_recent_scores,
        category_scores=category_scores,
        final_aps=final_aps,
        final_dashboard_scores=final_dashboard_scores,
        player_cols=player_cols,
    )

    return {
        "df": processed_df,
        "scoring_input": scoring_input,
        "benchmark_base": benchmark_base,
        "benchmark_source": benchmark_source,
        "benchmark_table": benchmark_table,
        "scoring_df": scoring_df,
        "assessment_recent_scores": assessment_recent_scores,
        "category_scores": category_scores,
        "final_aps": final_aps,
        "final_dashboard_scores": final_dashboard_scores,
        "diagnostics": diagnostics,
        "player_cols": player_cols,
    }


# ============================================================
# 8. SCRIPT ENTRY POINT
# ============================================================


if __name__ == "__main__":
    outputs = run_aps_scoring()

    print("APS scoring complete.")
    print(f"Rows used for scoring: {len(outputs['scoring_df']):,}")
    print(
        "Unmapped rows excluded from scoring: "
        f"{(outputs['df']['aps_category'] == 'Unmapped').sum():,}"
    )

    print("\nAvailable diagnostics:")
    print(list(outputs["diagnostics"].keys()))

    print("\nFinal dashboard scores preview:")
    print(outputs["final_dashboard_scores"].head())
