# -*- coding: utf-8 -*-
"""sigmoid_cohort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2h8jPaMC-EKyb94HNqT0gklzA5wN7hi
"""

# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np

# =============================
# 1. LOAD AND PREPROCESS DATA
# =============================

file_name = 'training_session.csv'
df = pd.read_csv(file_name, header=None)

# Assign 8 column names
df.columns = [
    'first_name', 'last_name', 'gender', 'col_d',
    'category', 'assessment', 'score', 'timestamp'
]

# Convert types
df['score'] = pd.to_numeric(df['score'], errors='coerce')
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

# Drop rows with missing score
df = df.dropna(subset=['score']).copy()

# Clean text columns
text_cols = ['first_name', 'last_name', 'gender', 'col_d', 'category', 'assessment']
for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

# Combine category and assessment
df['category_assessment'] = df['category'] + ' ' + df['assessment']

# Map age groups
age_map = {
    'A': 1, 'B': 1,
    'C': 2, 'D': 2,
    'E': 3, 'F': 3
}
df['age_group'] = df['col_d'].map(age_map)

# Standardize gender
df['gender_clean'] = df['gender'].str.upper().str[0]

# Keep only M / F if possible
df['gender_clean'] = df['gender_clean'].replace({
    'M': 'M',
    'F': 'F'
})

# Create cohort column
df['cohort'] = df['age_group'].astype('Int64').astype(str) + "_" + df['gender_clean']

# Drop rows with invalid cohort pieces
df = df[
    df['age_group'].notna() &
    df['gender_clean'].isin(['M', 'F'])
].copy()

# Optional: remove impossible or zero/negative scores if needed
# df = df[df['score'] > 0].copy()

print("Preprocessed shape:", df.shape)
df.head()

# ============================================
# LOG TRANSFORMATIONS
# ============================================

log_transform_assessments = [
    'Circuit Training Knockout',
    'Circuit Training Knockout-Obstacle',
    'Freelap 10yd Dash',
    'Freelap 10yd Dash Ball',
    'Freelap 20yd Dash',
    'Freelap 20yd Dash Ball',
    'RoxPro 5-10-5 shuttle',
    'RoxPro Sprint-10 yrd'
]

mask = df['category_assessment'].isin(log_transform_assessments)

df.loc[mask, 'score'] = np.log(
    pd.to_numeric(df.loc[mask, 'score'], errors='coerce')
)

# ============================================
# 2. DEFINE SCORE DIRECTION FOR EACH ASSESSMENT
# ============================================

higher_is_better_map = {
    # Lower is better
    'Broad Jump 5-10-5 Shuttles': False,
    'Circuit Training Knockout': False,
    'Circuit Training Knockout-Obstacle': False,
    'Freelap 10yd Dash': False,
    'Freelap 10yd Dash Ball': False,
    'Freelap 20yd Dash': False,
    'Freelap 20yd Dash Ball': False,
    'RoxPro 5-10-5 shuttle': False,
    'RoxPro Sprint-10 yrd': False,


    # Higher is better
    'Broad Jump Horizontal': True,
    'Circuit Training Maestro': True,
    'Circuit Training Pass Find 1': True,
    'Circuit Training Vision': True,
    'Fast Feet Architect': True,
    'Fast Feet Maestro': True,
    'Fast Feet Vision': True,
    'ICON 4M Architect': True,
    'ICON 4M Maestro': True,
    'ICON 4M Vision': True,
    'ICON Q Pass Find 2': True,
    'ICON V2 Architect': True,
    'ICON V2 Maestro': True,
    'ICON V2 Vision': True,
    'Reflexion Edge Hand Eye Coordination': True,
    'Reflexion Edge Inhibition': True,
    'Reflexion Edge Prioritization': True,
    'Reflexion Edge Reaction Time': True,
    'Reflexion Edge Tracking': True,
    'Tech Touch Ground & Tech Touch Air Receive 10 Air': True,
    'Tech Touch Ground & Tech Touch Air Receive 10 Ground': True,
    'Tech Touch One Touch Pass Pass 10 Air': True,
    'Tech Touch One Touch Pass Pass 10 Ground': True,
    'Vertical Jump Vertical': True,
    # Assessments from the new data
    'Circuit Maestro': True,
    'Circuit Vision': True,
    'Circuit Pass find 1': True,
    'ICON Q Pass find 2': True,
    'ICON 4M Vision': True,
    'ICON V2 Maestro': True,
    'TechTouch 1st Touch - Air': True,
    'TechTouch 1st touch - ground': True,
    'RoxPro 5-10-5 shuttle': False,
    'RoxPro Sprint-10 yrd': False,
    'Vision Wall GO 360': True,
    'Vision Wall Scan & React': True,
    'Vision Wall Large to Small': True,
    'Vision Wall Balance Reaction': True,
}

DEFAULT_HIGHER_IS_BETTER = True

df['higher_is_better'] = (
    df['category_assessment']
    .map(higher_is_better_map)
    .fillna(DEFAULT_HIGHER_IS_BETTER)
)

# ==========================================================
# 3. CREATE SCORING INPUT USING MOST RECENT PLAYER SCORE ONLY
# ==========================================================

# For APS and RPS, use only the most recent score for each player-assessment.
# This keeps your original df intact and creates a separate scoring_df.

player_cols = ['first_name', 'last_name', 'gender_clean', 'age_group']

scoring_df = (
    df.sort_values('timestamp')
      .drop_duplicates(subset=player_cols + ['category_assessment'], keep='last')
      .copy()
)

print("Scoring input shape (most recent attempt only):", scoring_df.shape)

import pandas as pd
import numpy as np

def compare_global_vs_cohort_sigmoid_rps(
    df,
    skill_col="category_assessment",
    score_col="score",
    cohort_col="cohort",
    age_group_col="age_group",
    gender_col="gender_clean",
    span_percentile=0.75,
    min_cohort_n=30,
    smoothing_lambda=0.70,
    skill_type_map=None,
    good_direction_map=None,
    clip_scores=True
):
    """
    Compare current global sigmoid RPS vs cohort-based sigmoid RPS.

    Final RPS is scaled to fall between 30 and 99:

        RPS = 30 + 69 * S(x)

    where S(x) is the sigmoid output between 0 and 1.
    """

    data = df.copy()

    # -----------------------------
    # 1. Basic cleaning
    # -----------------------------
    required_cols = [skill_col, score_col, cohort_col]
    for col in required_cols:
        if col not in data.columns:
            raise ValueError(f"Missing required column: {col}")

    data = data.dropna(subset=[skill_col, score_col, cohort_col]).copy()
    data[score_col] = pd.to_numeric(data[score_col], errors="coerce")
    data = data.dropna(subset=[score_col]).copy()

    if skill_type_map is None:
        skill_type_map = {}

    if good_direction_map is None:
        good_direction_map = {}

    data["skill_type"] = data[skill_col].map(skill_type_map).fillna("Normal")
    data["good_direction"] = data[skill_col].map(good_direction_map).fillna("Hi")

    # -----------------------------
    # 2. Transform score if Log skill
    # -----------------------------
    def safe_log(x):
        if x <= 0:
            return np.nan
        return np.log(x)

    data["score_model"] = np.where(
        data["skill_type"].eq("Log"),
        data[score_col].apply(safe_log),
        data[score_col]
    )

    data = data.dropna(subset=["score_model"]).copy()

    # -----------------------------
    # 3. Adjust direction
    # Higher should always mean better
    # -----------------------------
    data["score_oriented"] = np.where(
        data["good_direction"].eq("Lo"),
        -data["score_model"],
        data["score_model"]
    )

    # -----------------------------
    # 4. Sigmoid helper
    # -----------------------------
    # S_SPAN value for the 75th percentile
    S_SPAN = 1.0986

    # Business-facing score range
    RPS_MIN = 30
    RPS_MAX = 99
    RPS_RANGE = RPS_MAX - RPS_MIN

    def sigmoid(z):
        return 1 / (1 + np.exp(-z))

    def calculate_rps(x, mid, span):
        denom = abs(span - mid)

        if pd.isna(x) or pd.isna(mid) or pd.isna(span) or denom == 0:
            return np.nan

        z = S_SPAN * ((x - mid) / denom)

        # Sigmoid output between 0 and 1
        s_x = sigmoid(z)

        # Scale to 30 to 99
        score = RPS_MIN + RPS_RANGE * s_x

        if clip_scores:
            score = np.clip(score, RPS_MIN, RPS_MAX)

        return score

    # -----------------------------
    # 5. Global parameters by skill
    # -----------------------------
    global_params = (
        data
        .groupby(skill_col)
        .agg(
            global_n=("score_oriented", "size"),
            global_mid=("score_oriented", "median"),
            global_span=("score_oriented", lambda x: x.quantile(span_percentile)),
            global_p25=("score_oriented", lambda x: x.quantile(0.25)),
            global_p75=("score_oriented", lambda x: x.quantile(0.75)),
            skill_type=("skill_type", "first"),
            good_direction=("good_direction", "first")
        )
        .reset_index()
    )

    # -----------------------------
    # 6. Cohort parameters by skill and cohort
    # -----------------------------
    cohort_params = (
        data
        .groupby([skill_col, cohort_col])
        .agg(
            cohort_n=("score_oriented", "size"),
            cohort_mid=("score_oriented", "median"),
            cohort_span=("score_oriented", lambda x: x.quantile(span_percentile)),
            cohort_p25=("score_oriented", lambda x: x.quantile(0.25)),
            cohort_p75=("score_oriented", lambda x: x.quantile(0.75))
        )
        .reset_index()
    )

    cohort_params = cohort_params.merge(
        global_params[
            [
                skill_col,
                "global_n",
                "global_mid",
                "global_span",
                "skill_type",
                "good_direction"
            ]
        ],
        on=skill_col,
        how="left"
    )

    # -----------------------------
    # 7. Smooth cohort parameters
    # -----------------------------
    cohort_params["cohort_is_small"] = cohort_params["cohort_n"] < min_cohort_n

    cohort_params["effective_lambda"] = np.where(
        cohort_params["cohort_is_small"],
        smoothing_lambda,
        1.0
    )

    cohort_params["cohort_mid_smoothed"] = (
        cohort_params["effective_lambda"] * cohort_params["cohort_mid"]
        + (1 - cohort_params["effective_lambda"]) * cohort_params["global_mid"]
    )

    cohort_params["cohort_span_smoothed"] = (
        cohort_params["effective_lambda"] * cohort_params["cohort_span"]
        + (1 - cohort_params["effective_lambda"]) * cohort_params["global_span"]
    )

    # -----------------------------
    # 8. Merge parameters back
    # -----------------------------
    result_df = data.merge(
        global_params[[skill_col, "global_mid", "global_span", "global_n"]],
        on=skill_col,
        how="left"
    )

    result_df = result_df.merge(
        cohort_params[
            [
                skill_col,
                cohort_col,
                "cohort_n",
                "cohort_mid",
                "cohort_span",
                "cohort_mid_smoothed",
                "cohort_span_smoothed",
                "cohort_is_small",
                "effective_lambda"
            ]
        ],
        on=[skill_col, cohort_col],
        how="left"
    )

    # -----------------------------
    # 9. Calculate RPS
    # -----------------------------
    result_df["rps_global_sigmoid"] = result_df.apply(
        lambda row: calculate_rps(
            row["score_oriented"],
            row["global_mid"],
            row["global_span"]
        ),
        axis=1
    )

    result_df["rps_cohort_sigmoid"] = result_df.apply(
        lambda row: calculate_rps(
            row["score_oriented"],
            row["cohort_mid_smoothed"],
            row["cohort_span_smoothed"]
        ),
        axis=1
    )

    result_df["rps_difference"] = (
        result_df["rps_cohort_sigmoid"] - result_df["rps_global_sigmoid"]
    )

    result_df["abs_rps_difference"] = result_df["rps_difference"].abs()

        # -----------------------------
    # 9B. Calculate overall RPS using recency-weighted attempts
    # -----------------------------

    player_cols = ["first_name", "last_name", gender_col, age_group_col]
    timestamp_col = "timestamp"

    required_overall_cols = player_cols + [timestamp_col]

    for col in required_overall_cols:
        if col not in result_df.columns:
            raise ValueError(f"Missing required column for overall RPS: {col}")

    result_df[timestamp_col] = pd.to_datetime(result_df[timestamp_col], errors="coerce")
    result_df = result_df.dropna(subset=[timestamp_col]).copy()

    # Sort newest attempt first within each player and assessment
    sort_cols = player_cols + [skill_col, timestamp_col]

    result_df = result_df.sort_values(
        sort_cols,
        ascending=[True] * (len(player_cols) + 1) + [False]
    ).copy()

    # Count how many times each player took each assessment
    result_df["attempt_count"] = (
        result_df
        .groupby(player_cols + [skill_col])[skill_col]
        .transform("size")
    )

    # Rank attempts by recency
    result_df["attempt_recency_rank"] = (
        result_df
        .groupby(player_cols + [skill_col])
        .cumcount() + 1
    )

    # Keep only the most recent 3 attempts
    result_df["use_for_overall_rps"] = result_df["attempt_recency_rank"] <= 3

    # Assign recency weights
    def assign_attempt_weight(row):
        attempt_count = row["attempt_count"]
        rank = row["attempt_recency_rank"]

        if rank > 3:
            return 0.0

        if attempt_count == 1:
            return 1.0

        if attempt_count == 2:
            return 2 / 3 if rank == 1 else 1 / 3

        # If taken 3 or more times
        if rank == 1:
            return 0.50
        elif rank == 2:
            return 0.30
        elif rank == 3:
            return 0.20

        return 0.0

    result_df["attempt_weight"] = result_df.apply(assign_attempt_weight, axis=1)

    # Weighted RPS contribution within each player-assessment
    result_df["weighted_global_rps"] = (
        result_df["rps_global_sigmoid"] * result_df["attempt_weight"]
    )

    result_df["weighted_cohort_rps"] = (
        result_df["rps_cohort_sigmoid"] * result_df["attempt_weight"]
    )

    # Assessment-level weighted RPS for each player
    player_assessment_rps = (
        result_df[result_df["use_for_overall_rps"]]
        .groupby(player_cols + [skill_col], as_index=False)
        .agg(
            assessment_global_rps=("weighted_global_rps", "sum"),
            assessment_cohort_rps=("weighted_cohort_rps", "sum"),
            attempts_used_for_rps=("attempt_recency_rank", "max"),
            total_attempts=("attempt_count", "max")
        )
    )

    # Overall RPS = average across assessments
    overall_player_rps = (
        player_assessment_rps
        .groupby(player_cols, as_index=False)
        .agg(
            overall_global_rps=("assessment_global_rps", "mean"),
            overall_cohort_rps=("assessment_cohort_rps", "mean"),
            number_of_assessments=(skill_col, "nunique")
        )
    )
    # -----------------------------
    # 10. Diagnostics
    # -----------------------------
    overall_comparison = pd.DataFrame({
        "metric": [
            "number_of_records",
            "number_of_skills",
            "number_of_cohorts",
            "avg_global_rps",
            "avg_cohort_rps",
            "avg_difference",
            "median_difference",
            "avg_absolute_difference",
            "correlation_global_vs_cohort",
            "pct_records_diff_gt_5",
            "pct_records_diff_gt_10",
            "pct_small_cohort_records"
        ],
        "value": [
            len(result_df),
            result_df[skill_col].nunique(),
            result_df[cohort_col].nunique(),
            result_df["rps_global_sigmoid"].mean(),
            result_df["rps_cohort_sigmoid"].mean(),
            result_df["rps_difference"].mean(),
            result_df["rps_difference"].median(),
            result_df["abs_rps_difference"].mean(),
            result_df[["rps_global_sigmoid", "rps_cohort_sigmoid"]].corr().iloc[0, 1],
            (result_df["abs_rps_difference"] > 5).mean(),
            (result_df["abs_rps_difference"] > 10).mean(),
            result_df["cohort_is_small"].mean()
        ]
    })

    skill_comparison = (
        result_df
        .groupby(skill_col)
        .agg(
            n=(score_col, "size"),
            global_rps_mean=("rps_global_sigmoid", "mean"),
            cohort_rps_mean=("rps_cohort_sigmoid", "mean"),
            avg_difference=("rps_difference", "mean"),
            median_difference=("rps_difference", "median"),
            avg_abs_difference=("abs_rps_difference", "mean"),
            pct_diff_gt_5=("abs_rps_difference", lambda x: (x > 5).mean()),
            pct_diff_gt_10=("abs_rps_difference", lambda x: (x > 10).mean()),
            min_cohort_n=("cohort_n", "min"),
            max_cohort_n=("cohort_n", "max")
        )
        .reset_index()
        .sort_values("avg_abs_difference", ascending=False)
    )

    cohort_comparison = (
        result_df
        .groupby(cohort_col)
        .agg(
            n=(score_col, "size"),
            global_rps_mean=("rps_global_sigmoid", "mean"),
            cohort_rps_mean=("rps_cohort_sigmoid", "mean"),
            avg_difference=("rps_difference", "mean"),
            median_difference=("rps_difference", "median"),
            avg_abs_difference=("abs_rps_difference", "mean"),
            pct_diff_gt_5=("abs_rps_difference", lambda x: (x > 5).mean()),
            pct_diff_gt_10=("abs_rps_difference", lambda x: (x > 10).mean())
        )
        .reset_index()
        .sort_values("avg_abs_difference", ascending=False)
    )

    stability_table = (
        cohort_params
        .copy()
        .sort_values(["cohort_is_small", "cohort_n"], ascending=[False, True])
    )

    largest_changes = (
        result_df
        .sort_values("abs_rps_difference", ascending=False)
        [
            [
                skill_col,
                cohort_col,
                score_col,
                "skill_type",
                "good_direction",
                "cohort_n",
                "rps_global_sigmoid",
                "rps_cohort_sigmoid",
                "rps_difference",
                "abs_rps_difference"
            ]
        ]
        .head(50)
    )

    monotonicity_issues = []

    for skill, temp in result_df.groupby(skill_col):
        temp = temp.sort_values("score_oriented")

        global_diff = temp["rps_global_sigmoid"].diff().dropna()
        cohort_diff = temp.groupby(cohort_col)["rps_cohort_sigmoid"].diff().dropna()

        if (global_diff < -1e-8).any():
            monotonicity_issues.append({
                "skill": skill,
                "system": "global",
                "issue": "RPS decreases when oriented score increases"
            })

        if (cohort_diff < -1e-8).any():
            monotonicity_issues.append({
                "skill": skill,
                "system": "cohort",
                "issue": "RPS decreases within cohort when oriented score increases"
            })

    monotonicity_check = pd.DataFrame(monotonicity_issues)

    diagnostics = {
      "overall_comparison": overall_comparison,
      "skill_comparison": skill_comparison,
      "cohort_comparison": cohort_comparison,
      "stability_table": stability_table,
      "largest_changes": largest_changes,
      "monotonicity_check": monotonicity_check,
      "player_assessment_rps": player_assessment_rps,
      "overall_player_rps": overall_player_rps
}

    return result_df, global_params, cohort_params, diagnostics

skill_type_map = {
    "Circuit Training Knockout": "Log",
    "Circuit Training Knockout-Obstacle": "Log",
    "Freelap-10yd Dash": "Log",
    "Freelap-10yd Dash Ball": "Log",
    "Freelap-20yd Dash": "Log",
    "Freelap-20yd Dash Ball": "Log",
    "RoxPro 5-10-5 shuttle": "Log",
    "RoxPro Sprint-10 yrd": "Log"
}

good_direction_map = {
    "Circuit Training Knockout": "Lo",
    "Circuit Training Knockout-Obstacle": "Lo",
    "Freelap-10yd Dash": "Lo",
    "Freelap-10yd Dash Ball": "Lo",
    "Freelap-20yd Dash": "Lo",
    "Freelap-20yd Dash Ball": "Lo",
    "Broad Jump-5-10-5 Shuttles": "Lo",
    "RoxPro 5-10-5 shuttle": "Lo",
    "RoxPro Sprint-10 yrd": "Lo"
}

result_df, global_params, cohort_params, diagnostics = compare_global_vs_cohort_sigmoid_rps(
    df,
    skill_col="category_assessment",
    score_col="score",
    cohort_col="cohort",
    age_group_col="age_group",
    gender_col="gender_clean",
    span_percentile=0.75,
    min_cohort_n=30,
    smoothing_lambda=0.70,
    skill_type_map=skill_type_map,
    good_direction_map=good_direction_map
)

diagnostics.keys()

diagnostics["overall_player_rps"]

diagnostics["player_assessment_rps"]